### ISSUE TITLE
Address not found

### ISSUE THREAD

**Issue by adilhayat17** [pelias/openstreetmap#502] opened 2019-09-13 15:30 UTC
I have OSM, OA, Tiger, WOF importers downloaded for MD and PA states of USA. But I am not able to get "1111 MD 760, Lusby, MD, USA" or even "MD 760, Lusby, MD, USA" on my local environment. But on demo link
[https://pelias.github.io/compare/#/v1/search%3Ftext=1111 MD 760, Lusby, MD, USA](url)
I get source as OSM for "MD 760, Lusby, MD, USA" address.
Today I downloaded again OSM and prepare all and import but no success with me. 
My OSM source in config is 
`"sourceURL": "https://download.geofabrik.de/north-america/us/maryland-latest.osm.pbf"`
How can I get it. please can some one help me on it. Thanks.

**Comment by orangejulius** [comment] 2019-09-13 15:33
hi @adilhayat17 please do not open duplicate issues for the same issue.

Duplicate of https://github.com/pelias/docker/issues/132

**Closed by orangejulius** 2019-09-13 15:33 UTC
